language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "Bvcr5+PlixMZy2Kyr96xf3BxMTESpmbfbDnCSCZrpE88fvPGOUj2fxJZcU1cr/LYjfktxPyHPUuC1+mQMnhGgL3+x/XyAjvpnSxywZ9a+F0D3h66GwaIDova/lPeKTpnJtjUHUHq4X2Q88tTNBs0Lgl/r6btrOl9CThRvTbsFrT+i1yYUXGQjJrJSUQ0B2IuRq430QeCVv/sfXbjyMOyg4StKfGNfkZ5TjEU9bdOHVcSgqIsGkeMgXS9is1i7Fu7+Ze7WL+iwrxbWkABqfnPRwohSLQPfVX0BavM0aSzHuy6V64psK/OshMhHd5knhtzWVxUj5oCVr14CsgzPxXJb1uf/Tt9bPp6zC39o6XDff123lePXbVkdcEdENDpudXOocrTtdAmoa/0q7p+ELjfjRkgNNi2LJzW0NjJnQEmP+cyXXL2dit8P22gO+caoYuFhGrpVRMwUA0NOXz3aRf+BGJr2p8kjjF4TQpU21D2EW+fvtLq6/G486Bft+YURdwsbc2dh7Pnag2eS8y5X/KsYz+9xJKZHCjQSOu9P9ax0r8n8BpN/e1dLvqpCsqUgrcAAb4HDYt7IGnlgwSzVWVcp9M6sCWCxoP0SKhN9JRLjdkWsoc/jCbr3LuXZiAGTbysAKGRzdQdKfZxszyTdFak1iD9ZCnWjQtx/pCzEPddQK4="
    - secure: "G/FivJKgVaghPGR/fggCLdNgJlmX9bfqu/zpv/MTFVH1GxaV3xK3iw3GSJAN1Wplsi76/eQJvBMK7pBx5U/n00lOAx7BOKSo8jF4a7qnIPz4+u3ylujvUBHLQXdxbzCVzR6G6xHAKZ3EhhIxyCB9Od8dMV3nzOl3P6BWL7ZqR8VX5axHfNhO16qNxPwLIsE+2ryvKlGAP9HssNKMrd5rvucM83IWpzmrqq5bTlkZPcbYgPkkad3pNAvcbVEK6txRWhu9+abIVE1pvXVRcJWw25KTvdg3y64FOw81FIlxYxiGjQj1/TyKZnEIOedapkRx401mqNk0cEDlfcn7MV+lT0IG6YI/0b9KsKsuPCg32kDCepzuO7lNNn1IBIM3lc9BfdnjpwCzrGtJWNMfpbefLVIYsN+csmmQAE3LecdGTDVq2EUQLN27CXcWV4YaApSpuOknL6IDGEMVBpDUA+o1skCTfhUr1rFSwvE5rZNBBjyxhCPbL029dBjDSes4sdGYJPjuyGd05TRoXjVvgcqQMPlB3l9bLyloSoaXxDLhKF4f0snjlt6pQp0Xe7+FsRF4PkAuxD92izGjwMogHUTs1s4rbOTg11XA2ZDczpt8Yphau3e4jxFChhwIwKbQAO+VjYQgEOk+Us7gQHwvn9TBKLlTdjDHUI+3XLS2QnJ+TA8="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false
